FROM centos:7

# Install devtoolset-7 (gcc 7)
RUN yum install -y centos-release-scl && \
    yum install -y devtoolset-7

ENV PATH /opt/rh/devtoolset-7/root/usr/bin:$PATH
ENV LD_LIBRARY_PATH /opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:$LD_LIBRARY_PATH

# Build command
# > docker build -f Dockerfile.gcc7 -t compiler/gcc:7.2.1 .
