# ESMA Baselibs and its dependencies (gcc, openmpi, anaconda)
FROM pchakraborty/esma-baselibs:5.2.4

# Intel MKL
COPY --from=pchakraborty/intel-mkl:2019.1.144 /opt/intel /opt/intel
ENV MKLPATH /opt/intel/compilers_and_libraries/linux/mkl/lib/intel64

# Some more dependencies
RUN yum install -y perl-Env tcsh

# Build command
# > docker build -f Dockerfile.geos-build-env -t pchakraborty/geos-build-env:<version> .
